### ISSUE TITLE
add second page

### ISSUE THREAD

**Issue by tonycalderoney** [kiyanpourmaleki/Poker-Champ#15]
let's build off what we have and add a second page. doesn't have to be crazy but to start maybe store the player's name and code and then display it on a new page.

**Comment by kiyanpourmaleki** [comment]
load into a game? set up the layout for when a player is in game. this can be a lot but start simple. table and dealer in background. button to exit to lobby. this will become more as we go

**Comment by kiyanpourmaleki** [comment]
second page check
